SRC_FILES += \
	$(HP_DIR)/src/hp_manager.c \
	$(HP_DIR)/src/hp_applicator.c \
	$(HP_DIR)/src/hp_code.c \
	$(HP_DIR)/src/hp_guard.c \
	$(HP_DIR)/src/hp_slot.c \
	$(HP_DIR)/src/hp_freertos_mpu.c \
	$(HP_DIR)/src/hp_exception.c \
	$(HP_DIR)/src/hp_measure.c

INC_FOLDERS += \
	$(HP_DIR)/include 